{{- if and .Values.oidc.enabled .Values.oidc.session.autoGenerate }}
{{- $secretName := printf "%s-session-secret" (include "quine-enterprise.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "quine-enterprise.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  secret: {{ randAlphaNum 45 | b64enc | quote }}
  {{- else }}
  secret: {{ index $existingSecret.data "secret" }}
  {{- end }}
{{- end }}
