{{- if and .Values.oidc.enabled .Values.oidc.session.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novelty.fullname" . }}-session-secret
  labels:
    {{- include "novelty.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ randAlphaNum 45 | b64enc | quote }}
{{- end }}
